spring:
  application:
    name: unit-test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

